# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IFS2.ui'
#
# Created: Sun Apr 26 19:59:36 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(516, 384)
        self.formLayout = QtGui.QFormLayout(Dialog)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.buttonBox)
        self.About = QtGui.QTabWidget(Dialog)
        self.About.setObjectName(_fromUtf8("About"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.StartButton = QtGui.QPushButton(self.tab)
        self.StartButton.setObjectName(_fromUtf8("StartButton"))
        self.gridLayout_4.addWidget(self.StartButton, 0, 0, 1, 1)
        self.doit = QtGui.QLineEdit(self.tab)
        self.doit.setObjectName(_fromUtf8("doit"))
        self.gridLayout_4.addWidget(self.doit, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.SetRatio = QtGui.QPushButton(self.tab)
        self.SetRatio.setObjectName(_fromUtf8("SetRatio"))
        self.gridLayout_2.addWidget(self.SetRatio, 3, 1, 1, 1)
        self.SetFlowLimit = QtGui.QPushButton(self.tab)
        self.SetFlowLimit.setObjectName(_fromUtf8("SetFlowLimit"))
        self.gridLayout_2.addWidget(self.SetFlowLimit, 1, 1, 1, 1)
        self.spinBoxFlow = QtGui.QSpinBox(self.tab)
        self.spinBoxFlow.setMaximum(10000)
        self.spinBoxFlow.setObjectName(_fromUtf8("spinBoxFlow"))
        self.gridLayout_2.addWidget(self.spinBoxFlow, 1, 0, 1, 1)
        self.spinBoxRatio = QtGui.QSpinBox(self.tab)
        self.spinBoxRatio.setMaximum(100)
        self.spinBoxRatio.setSingleStep(1)
        self.spinBoxRatio.setObjectName(_fromUtf8("spinBoxRatio"))
        self.gridLayout_2.addWidget(self.spinBoxRatio, 3, 0, 1, 1)
        self.label3 = QtGui.QLabel(self.tab)
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout_2.addWidget(self.label3, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 2, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label1 = QtGui.QLabel(self.tab)
        self.label1.setObjectName(_fromUtf8("label1"))
        self.verticalLayout.addWidget(self.label1)
        self.repSend = QtGui.QTextEdit(self.tab)
        self.repSend.setObjectName(_fromUtf8("repSend"))
        self.verticalLayout.addWidget(self.repSend)
        self.label2 = QtGui.QLabel(self.tab)
        self.label2.setObjectName(_fromUtf8("label2"))
        self.verticalLayout.addWidget(self.label2)
        self.repRecieve = QtGui.QTextEdit(self.tab)
        self.repRecieve.setObjectName(_fromUtf8("repRecieve"))
        self.verticalLayout.addWidget(self.repRecieve)
        self.gridLayout_4.addLayout(self.verticalLayout, 1, 0, 3, 2)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 3, 1, 1)
        self.setInflow = QtGui.QLabel(self.tab)
        self.setInflow.setObjectName(_fromUtf8("setInflow"))
        self.gridLayout_3.addWidget(self.setInflow, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 1, 1, 1)
        self.setFlowsum = QtGui.QLabel(self.tab)
        self.setFlowsum.setObjectName(_fromUtf8("setFlowsum"))
        self.gridLayout_3.addWidget(self.setFlowsum, 3, 3, 1, 1)
        self.repFlowSum = QtGui.QLabel(self.tab)
        self.repFlowSum.setObjectName(_fromUtf8("repFlowSum"))
        self.gridLayout_3.addWidget(self.repFlowSum, 3, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 4, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 3, 0, 1, 1)
        self.lRepRatio = QtGui.QLabel(self.tab)
        self.lRepRatio.setObjectName(_fromUtf8("lRepRatio"))
        self.gridLayout_3.addWidget(self.lRepRatio, 4, 1, 1, 1)
        self.SetRatio_2 = QtGui.QLabel(self.tab)
        self.SetRatio_2.setObjectName(_fromUtf8("SetRatio_2"))
        self.gridLayout_3.addWidget(self.SetRatio_2, 4, 3, 1, 1)
        self.repInflow = QtGui.QLabel(self.tab)
        self.repInflow.setObjectName(_fromUtf8("repInflow"))
        self.gridLayout_3.addWidget(self.repInflow, 2, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 2, 2, 1, 1)
        self.MixProgress = QtGui.QProgressBar(self.tab)
        self.MixProgress.setProperty("value", 0)
        self.MixProgress.setObjectName(_fromUtf8("MixProgress"))
        self.gridLayout_4.addWidget(self.MixProgress, 3, 2, 1, 1)
        self.About.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 10, 471, 271))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.ResetButton = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.ResetButton.setObjectName(_fromUtf8("ResetButton"))
        self.gridLayout_5.addWidget(self.ResetButton, 0, 1, 1, 1)
        self.TestButton = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.TestButton.setObjectName(_fromUtf8("TestButton"))
        self.gridLayout_5.addWidget(self.TestButton, 1, 1, 1, 1)
        self.clearScreenButton = QtGui.QPushButton(self.gridLayoutWidget_3)
        self.clearScreenButton.setObjectName(_fromUtf8("clearScreenButton"))
        self.gridLayout_5.addWidget(self.clearScreenButton, 2, 1, 1, 1)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.Ref_Volt = QtGui.QLabel(self.gridLayoutWidget_3)
        self.Ref_Volt.setObjectName(_fromUtf8("Ref_Volt"))
        self.gridLayout_6.addWidget(self.Ref_Volt, 1, 1, 1, 1)
        self.Battery = QtGui.QLabel(self.gridLayoutWidget_3)
        self.Battery.setObjectName(_fromUtf8("Battery"))
        self.gridLayout_6.addWidget(self.Battery, 2, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.ServiceInfo = QtGui.QTextEdit(self.gridLayoutWidget_3)
        self.ServiceInfo.setObjectName(_fromUtf8("ServiceInfo"))
        self.gridLayout_5.addWidget(self.ServiceInfo, 2, 0, 1, 1)
        self.About.addTab(self.tab_2, _fromUtf8(""))
        self.HelpTab = QtGui.QWidget()
        self.HelpTab.setObjectName(_fromUtf8("HelpTab"))
        self.label_13 = QtGui.QLabel(self.HelpTab)
        self.label_13.setGeometry(QtCore.QRect(10, 260, 191, 17))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.HelpTab)
        self.label_14.setGeometry(QtCore.QRect(10, 240, 191, 17))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.HelpTab)
        self.label_15.setGeometry(QtCore.QRect(10, 220, 191, 17))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.Logo = QtGui.QGraphicsView(self.HelpTab)
        self.Logo.setGeometry(QtCore.QRect(10, 10, 256, 192))
        self.Logo.setObjectName(_fromUtf8("Logo"))
        self.About.addTab(self.HelpTab, _fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.About)

        self.retranslateUi(Dialog)
        self.About.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.StartButton.setText(_translate("Dialog", "Start", None))
        self.SetRatio.setText(_translate("Dialog", "Set", None))
        self.SetFlowLimit.setText(_translate("Dialog", "Set", None))
        self.label3.setText(_translate("Dialog", "Flow Limit [ml]", None))
        self.label_8.setText(_translate("Dialog", "Mixing Ratio [%]", None))
        self.label1.setText(_translate("Dialog", "Send", None))
        self.label2.setText(_translate("Dialog", "Recieve", None))
        self.label_4.setText(_translate("Dialog", "V [ml]", None))
        self.label_6.setText(_translate("Dialog", "V_max", None))
        self.setInflow.setText(_translate("Dialog", "....", None))
        self.label_2.setText(_translate("Dialog", "U [V]", None))
        self.setFlowsum.setText(_translate("Dialog", "....", None))
        self.repFlowSum.setText(_translate("Dialog", "0", None))
        self.label_11.setText(_translate("Dialog", "....", None))
        self.label_10.setText(_translate("Dialog", "....", None))
        self.label_12.setText(_translate("Dialog", "....", None))
        self.label_3.setText(_translate("Dialog", "MixingRatio", None))
        self.label_5.setText(_translate("Dialog", "Inflow", None))
        self.label.setText(_translate("Dialog", "FlowSum", None))
        self.lRepRatio.setText(_translate("Dialog", "0", None))
        self.SetRatio_2.setText(_translate("Dialog", "....", None))
        self.repInflow.setText(_translate("Dialog", "0", None))
        self.label_22.setText(_translate("Dialog", "Control", None))
        self.About.setTabText(self.About.indexOf(self.tab), _translate("Dialog", "Main", None))
        self.ResetButton.setText(_translate("Dialog", "Reset Bus", None))
        self.TestButton.setText(_translate("Dialog", "Test Valves", None))
        self.clearScreenButton.setText(_translate("Dialog", "Clear", None))
        self.label_9.setText(_translate("Dialog", "Battery", None))
        self.label_7.setText(_translate("Dialog", "Reference Voltage", None))
        self.Ref_Volt.setText(_translate("Dialog", "....", None))
        self.Battery.setText(_translate("Dialog", "....", None))
        self.About.setTabText(self.About.indexOf(self.tab_2), _translate("Dialog", "Service", None))
        self.label_13.setText(_translate("Dialog", "Contact: marcel.gaj@bgr.de", None))
        self.label_14.setText(_translate("Dialog", "Version 1.2", None))
        self.label_15.setText(_translate("Dialog", "Field Sampler ", None))
        self.About.setTabText(self.About.indexOf(self.HelpTab), _translate("Dialog", "About", None))
